# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/suzhou/Library/Android/sdk/cmake/3.22.1/bin/cmake

# The command to remove a file.
RM = /Users/suzhou/Library/Android/sdk/cmake/3.22.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/suzhou/workspace/demos/cpp_playground

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/suzhou/workspace/demos/cpp_playground

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Users/suzhou/Library/Android/sdk/cmake/3.22.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Users/suzhou/Library/Android/sdk/cmake/3.22.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/suzhou/workspace/demos/cpp_playground/CMakeFiles /Users/suzhou/workspace/demos/cpp_playground//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/suzhou/workspace/demos/cpp_playground/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named algorithm

# Build rule for target.
algorithm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 algorithm
.PHONY : algorithm

# fast build rule for target.
algorithm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/build
.PHONY : algorithm/fast

algorithm/sort/bubble.o: algorithm/sort/bubble.cpp.o
.PHONY : algorithm/sort/bubble.o

# target to build an object file
algorithm/sort/bubble.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/algorithm/sort/bubble.cpp.o
.PHONY : algorithm/sort/bubble.cpp.o

algorithm/sort/bubble.i: algorithm/sort/bubble.cpp.i
.PHONY : algorithm/sort/bubble.i

# target to preprocess a source file
algorithm/sort/bubble.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/algorithm/sort/bubble.cpp.i
.PHONY : algorithm/sort/bubble.cpp.i

algorithm/sort/bubble.s: algorithm/sort/bubble.cpp.s
.PHONY : algorithm/sort/bubble.s

# target to generate assembly for a file
algorithm/sort/bubble.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/algorithm/sort/bubble.cpp.s
.PHONY : algorithm/sort/bubble.cpp.s

algorithm/sort/quick.o: algorithm/sort/quick.cpp.o
.PHONY : algorithm/sort/quick.o

# target to build an object file
algorithm/sort/quick.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/algorithm/sort/quick.cpp.o
.PHONY : algorithm/sort/quick.cpp.o

algorithm/sort/quick.i: algorithm/sort/quick.cpp.i
.PHONY : algorithm/sort/quick.i

# target to preprocess a source file
algorithm/sort/quick.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/algorithm/sort/quick.cpp.i
.PHONY : algorithm/sort/quick.cpp.i

algorithm/sort/quick.s: algorithm/sort/quick.cpp.s
.PHONY : algorithm/sort/quick.s

# target to generate assembly for a file
algorithm/sort/quick.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/algorithm/sort/quick.cpp.s
.PHONY : algorithm/sort/quick.cpp.s

data_structure/btree.o: data_structure/btree.cpp.o
.PHONY : data_structure/btree.o

# target to build an object file
data_structure/btree.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/data_structure/btree.cpp.o
.PHONY : data_structure/btree.cpp.o

data_structure/btree.i: data_structure/btree.cpp.i
.PHONY : data_structure/btree.i

# target to preprocess a source file
data_structure/btree.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/data_structure/btree.cpp.i
.PHONY : data_structure/btree.cpp.i

data_structure/btree.s: data_structure/btree.cpp.s
.PHONY : data_structure/btree.s

# target to generate assembly for a file
data_structure/btree.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/data_structure/btree.cpp.s
.PHONY : data_structure/btree.cpp.s

data_structure/utils.o: data_structure/utils.cpp.o
.PHONY : data_structure/utils.o

# target to build an object file
data_structure/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/data_structure/utils.cpp.o
.PHONY : data_structure/utils.cpp.o

data_structure/utils.i: data_structure/utils.cpp.i
.PHONY : data_structure/utils.i

# target to preprocess a source file
data_structure/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/data_structure/utils.cpp.i
.PHONY : data_structure/utils.cpp.i

data_structure/utils.s: data_structure/utils.cpp.s
.PHONY : data_structure/utils.s

# target to generate assembly for a file
data_structure/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/algorithm.dir/build.make CMakeFiles/algorithm.dir/data_structure/utils.cpp.s
.PHONY : data_structure/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... algorithm"
	@echo "... algorithm/sort/bubble.o"
	@echo "... algorithm/sort/bubble.i"
	@echo "... algorithm/sort/bubble.s"
	@echo "... algorithm/sort/quick.o"
	@echo "... algorithm/sort/quick.i"
	@echo "... algorithm/sort/quick.s"
	@echo "... data_structure/btree.o"
	@echo "... data_structure/btree.i"
	@echo "... data_structure/btree.s"
	@echo "... data_structure/utils.o"
	@echo "... data_structure/utils.i"
	@echo "... data_structure/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

